---
# This playbook prints a simple debug message
- name: Echo
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Print debug message
      debug:
        msg: Hello, world! Ich bin {{ name-param }} aus {{ country-param }} und string ist {{HELLO_STRING}}
